name: build-pages

on:
  push:
    branches: [ master, test ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Compile
        if: ${{ !contains(github.event.head_commit.message, '[skip ci]') }}
        run: |
          export DEBIAN_FRONTEND=noninteractive
          sudo apt-get update -yqq
          sudo apt-get install npm sed make rsync -yqq > /dev/null 2>&1
          cp -r $GITHUB_WORKSPACE /tmp/repo
          cd /tmp/repo
          npm install
          npm run build
          DATE=`date -u`
          sed -i "s/Dev version/Generated at $DATE/" examples/without-vue.html
          sed -i "s/Dev version/Generated at $DATE/" examples/with-vue.html
          mkdir /tmp/pages
          cp -r js examples /tmp/pages/

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: /tmp/pages